permissions: &permissions
  permissions:
    # - group_name: steward
    #   level: CAN_MANAGE_RUN 
    - group_name: users
      level: CAN_VIEW

job_cluster: &job_cluster
  new_cluster:
    policy_id: ${var.job_cluster_policy}
    spark_version: 17.0.x-scala2.13
    driver_node_type_id: m5d.large
    node_type_id: m5d.large
    runtime_engine: STANDARD
    autoscale:
      min_workers: 1
      max_workers: 2
    aws_attributes:
      first_on_demand: 1
      availability: SPOT_WITH_FALLBACK
    custom_tags:
      bundle_name: description_checkings

resources:
  jobs:
    task:
      name: description_checkings-job
      <<: *permissions
      job_clusters:
        - job_cluster_key: description_checkings-job-cluster
          <<: *job_cluster
      tasks:
        - task_key: create_udfs
          job_cluster_key: description_checkings-job-cluster
          sql_task:
            file:
              path: ../src/create_udfs.sql
              source: WORKSPACE
            warehouse_id: ${var.warehouse_id}
