targets:
  dev:
    mode: development
    default: true
    presets:
      name_prefix: "[${var.git_branch} ${workspace.current_user.short_name}]"
    workspace:
      host: https://dbc-34699a31-e396.cloud.databricks.com
      root_path: /Workspace/Users/${workspace.current_user.userName}/.bundle/${var.git_branch}/${bundle.name}

  # prod:
  #   mode: production
  #   default: true
  #   workspace:
  #     host: https://dbc-34699a31-e396.cloud.databricks.com
  #     root_path: /Workspace/Users/${workspace.current_user.userName}/.bundle/${var.git_branch}/${bundle.name}
  #   run_as:
  #     service_principal_name: 