variables:
  common_requirements_path:
    description: Common dependent libraries in workspace.
    default: /Volumes/common/tools/artifacts/.internal/requirements.txt
  git_branch:
    description: Git branch name of the bundle to deploy.
    default: develop