permissions: &permissions
  permissions:
    # - group_name: steward
    #   level: CAN_MANAGE_RUN 
    - group_name: users
      level: CAN_VIEW

job_cluster: &job_cluster
  new_cluster:
    policy_id: ${var.job_cluster_policy}
    spark_version: 17.0.x-scala2.13
    driver_node_type_id: m5d.large
    node_type_id: m5d.large
    runtime_engine: STANDARD
    autoscale:
      min_workers: 1
      max_workers: 2
    aws_attributes:
      first_on_demand: 1
      availability: SPOT_WITH_FALLBACK
    custom_tags:
      bundle_name: datasteward_description_settings

resources:
  jobs:
    batch_job:
      name: description_settings-job-batch
      <<: *permissions
      job_clusters:
        - job_cluster_key: description_settings-job-batch-cluster
          <<: *job_cluster
      tasks:
        - task_key: main
          job_cluster_key: description_settings-job-batch-cluster
          notebook_task:
            notebook_path: ../src/main.ipynb
          parameters:
            - name: SOURCE_TABLE
              default: ${var.source_table}
            - name: SQL_TEXT
              default: ${var.sql_text}
