name: Deploy to the development

concurrency: 1

on:
  push:
    branches-ignore:
      - develop
      - master
    paths-ignore:
      - ".github/**"
      - "README.md"

jobs:
  set_list:
    uses: ./.github/workflows/grep_bundles.yaml

  get_branch:
    runs-on: [self-hosted, organization]
    outputs:
      bundles: ${{ steps.get_branch.outputs.branch }}
    steps:
      - name: Checkout code into workspace directory
        uses: actions/checkout@v4
      - id: get_branch
        run: |
          branch=$(git branch --show-current | tr '/' '-')
          echo "branch=$branch" >> $GITHUB_OUTPUT
      - name: Print branch name
        run: echo ${{ steps.get_branch.outputs.branch }}

  deploy_bundles:
    needs: [set_list, get_branch]
    if: needs.set_list.outputs.bundles != '[]'
    strategy:
      fail-fast: false
      matrix:
        bundle: ${{ fromJSON(needs.set_list.outputs.bundles )}}
    uses: ./.github/workflows/deploy_bundle.yaml
    with:
      stage: dev
      bundle: ${{ matrix.bundle }}
      git_branch: ${{ needs.get_branch.outputs.branch }}
    secrets: inherit